{"name": "test_get_order_of_his_number_with__non_existent_error", "status": "passed", "description": "Проверка невозможности получить заказ, если отправить несуществующий номер. Получаем код 404 и сообщение: Заказ не найден", "steps": [{"name": "Получить заказ по его номеру", "status": "passed", "parameters": [{"name": "track_number", "value": "'0'"}], "start": 1716822789823, "stop": 1716822789936}], "start": 1716822789823, "stop": 1716822789937, "uuid": "1704f9c9-cce1-4ab5-882d-337f8fd67510", "historyId": "46c097b163a33b4760b55f8dbadd14fa", "testCaseId": "46c097b163a33b4760b55f8dbadd14fa", "fullName": "tests.test_get_order_of_his_number.TestGetOrder#test_get_order_of_his_number_with__non_existent_error", "labels": [{"name": "suite", "value": "Ручка /api/v1/orders/track"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "LAPTOP-K"}, {"name": "thread", "value": "11960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_of_his_number"}]}